#!/usr/bin/env python3
# -*- coding: utf-8 -*-
PAGE_DATA = {
    "current_user": {
        "name": "管理员",
    },
    "vmlist": [
        {
            "id": 1,
            "name": "Weblogic 中间件服务",
            "ip": "172.100.10.6",
            "ports": "80, 443",
            "cpu": "50",
            "status": "ok",
        },
        {
            "id": 2,
            "name": "Rocket.Chat 内网协作平台",
            "ip": "172.101.9.3",
            "ports": "80",
            "cpu": "35",
            "status": "ok",
        },
        {
            "id": 3,
            "name": "ownCloud 内网云盘",
            "ip": "172.101.100.2",
            "ports": "22, 80, 445, 8080",
            "cpu": "90",
            "status": "error",
        },
        {
            "id": 4,
            "name": "TensorFlow 内网 AI 平台",
            "ip": "172.50.10.6",
            "ports": "80, 443",
            "cpu": "60",
            "status": "ok",
        },
        {
            "id": 5,
            "name": "Piwik 网页分析工具",
            "ip": "172.20.10.7",
            "ports": "80, 443, 22",
            "cpu": "25",
            "status": "ok",
        },
        {
            "id": 6,
            "name": "Zabbix 业务监控平台",
            "ip": "172.100.10.6",
            "ports": "22, 80, 443, 3306",
            "cpu": "60",
            "status": "ok",
        },
        {
            "id": 7,
            "name": "Gitlab 版本控制服务",
            "ip": "172.10.210.120",
            "ports": "80, 3306, 445",
            "cpu": "72",
            "status": "ok",
        },
        {
            "id": 8,
            "name": "Jenkins CI 持续集成服务",
            "ip": "172.10.120.100",
            "ports": "80, 443",
            "cpu": "30",
            "status": "ok",
        },
        {
            "id": 9,
            "name": "Odoo 企业 CRM 系统",
            "ip": "172.50.120.3",
            "ports": "80, 3306",
            "cpu": "65",
            "status": "ok",
        },
    ],
}
